Homework 1
ok-technopolis-autumn-2022/Emelyanov_Pavel pull request #1
Opened 2022-09-30 00:22 UTC by llav3ji2019

2022-09-30 08:15 UTC, fromanywhere requested changes
В целом сделано неплохо — чистенько, есть заход на семантику (нужно доработать), все управляющие элементы стоят на своих местах. Можно было бы, конечно, и побольше тегов понапридумывать, но и так нормально

Когда поправите замечания, оставьте, пожалуйста, висеть pr открытым — после следующей лекции будем вносить доработки прямо сюда

2022-09-30 08:15 UTC, fromanywhere commented on index.html
> +        <section class="todos_page">
Попытка была неплохой, но, всё же, скорее section будет внутри main, чем наоборот

2022-09-30 08:15 UTC, fromanywhere commented on index.html
> +                    <ul class="marked_list">
здесь тоже: ul — хорошо, div как прямой потомок ul — плохо

2022-09-30 08:15 UTC, fromanywhere commented on index.html
> +                            <input type="radio">
Если мы делаем радиокнопками, нужно позаботиться о том, чтобы в один момент времени могла быть выбрана только одна из них (как?)

2022-09-30 10:05 UTC, llav3ji2019 commented on index.html
> +                    <ul class="marked_list">
Тогда там точка появлялась перед checkbox, поэтому я убрал теги <li>

2022-09-30 10:07 UTC, fromanywhere commented on index.html
> +                    <ul class="marked_list">
Это ок, стилизация будет потом

2022-09-30 10:09 UTC, llav3ji2019 commented on index.html
> +                            <input type="radio">
Надо указать name, чтобы брузер понял, что эти кнопки были связаны между собой

2022-10-05 10:30 UTC, fromanywhere requested changes

2022-10-05 10:30 UTC, fromanywhere commented on index.html
> +                    <div>
Здесь лучше описать эту группу людям с читалками. role=radiogroup , aria-label

2022-10-07 00:18 UTC, llav3ji2019 commented on index.html
> +                    <div>
добавил доступность

2022-10-07 12:12 UTC, fromanywhere approved these changes

2022-10-10 18:10 UTC, merged