Homework2
ok-technopolis-autumn-2022/Emelyanov_Pavel pull request #2
Opened 2022-10-19 02:51 UTC by llav3ji2019

2022-10-19 07:56 UTC, fromanywhere requested changes
Потерялись кнопки удаления

При увеличении количества элементов футер начинает накладываться на них сверху

Очень далеко от макета

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  display: none;
чекбокс не ловит клавиатурный фокус

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  background-image: url("../images/completed.png");
на ретине картинка мыльная

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  width: calc(100% - 30px);
в этом макете нет мест, где было бы разумно использовать calc

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  visibility: hidden;
клавиатурный фокус не ловится

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  max-width: 40vw;
зачем здесь единицы от вьюпорта?

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +.footer__item-in-footer:nth-child(3n) {
нет причин использовать nth-child в этом макете

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  border: 1px solid #ebdfdf;
при переключении между фильтрами надписи дергаются по горизонтали. Нужно придумать, как сделать, чтобы не дергались

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  width: 20px;
увеличиваем площади интерактивных элементов

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +span.footer__radio-button-text {
а в чем идея увеличивать специфичность селектором по тегу?

2022-10-19 07:56 UTC, fromanywhere commented on css/styles.css
> +  border: none;
увеличиваем площадь интерактивных элементов — растягиваем инпут в размер ячейки

2022-10-19 11:50 UTC, llav3ji2019 commented on css/styles.css
> +  display: none;
исправил

2022-10-24 16:16 UTC, llav3ji2019 commented on css/styles.css
> +  width: calc(100% - 30px);
исправил

2022-10-24 16:17 UTC, llav3ji2019 commented on css/styles.css
> +  visibility: hidden;
испрваил

2022-10-24 16:17 UTC, llav3ji2019 commented on css/styles.css
> +  max-width: 40vw;
исправил

2022-10-24 16:46 UTC, llav3ji2019 commented on css/styles.css
> +  border: 1px solid #ebdfdf;
испрваил

2022-10-24 16:50 UTC, llav3ji2019 commented on css/styles.css
> +.footer__item-in-footer:nth-child(3n) {
а можно его использовать для надписей All, Completed, Active?(я задаю отступ слева и справа для элемента по середине)

2022-10-24 17:01 UTC, llav3ji2019 commented on css/styles.css
> +span.footer__radio-button-text {
исправил

2022-10-24 17:27 UTC, llav3ji2019 commented on css/styles.css
> +  max-width: 40vw;
но это было, чтобы на всех устройствах это выглядело примерно одинаково

2022-10-24 17:57 UTC, llav3ji2019 commented on css/styles.css
> +  width: 20px;
можно пояснить?

2022-10-25 10:09 UTC, fromanywhere commented on css/styles.css
> +.footer__item-in-footer:nth-child(3n) {
Вероятно, флексы решат Вашу проблему изящнее

2022-10-25 10:10 UTC, fromanywhere commented on css/styles.css
> +  width: 20px;
нужно сделать плозади кнопок и полей ввода настолько большими, насколько возможно
Например, для того, чтобы люди с телефона могли попасть в них пальцем

2022-10-30 23:50 UTC, llav3ji2019 commented on css/styles.css
> +  background-image: url("../images/completed.png");
исправил

2022-10-31 02:58 UTC, llav3ji2019 commented on css/styles.css
> +  width: 20px;
исправил

2022-10-31 02:58 UTC, llav3ji2019 commented on css/styles.css
> +  border: none;
исправил

2022-10-31 10:44 UTC, fromanywhere requested changes

2022-10-31 10:44 UTC, fromanywhere commented on css/styles.css
> +  margin-top: -99999px;
а в каком случае она становится видимой?

2022-10-31 10:44 UTC, fromanywhere commented on css/styles.css
> +  position: absolute;
сейчас при навигации фокус попадает в невидимый контрол, и непонятно, что происходит. Я предлагаю убрать поле ввода из клавиатурной навигации до  момента, когда мы будем работать с js

2022-10-31 10:44 UTC, fromanywhere commented on css/styles.css
> +  position: absolute;
<img width="638" alt="image" src="https://user-images.githubusercontent.com/1042969/198989931-50c840f5-adbc-4dba-863e-d636330e6cc7.png">

2022-10-31 10:44 UTC, fromanywhere commented on css/styles.css
> +  height: 20px;
высота не по макету

2022-10-31 10:44 UTC, fromanywhere commented on css/styles.css
> +  color: #666666;
нужно увеличить кликабельную зону кнопки (например, увеличив её высоту)

2022-10-31 10:44 UTC, fromanywhere commented on css/styles.css
> +  top: 10px;
Очень странный отступ 
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1042969/198990231-1341fc7c-189d-451d-a4ce-35cfa619c1e3.png">

2022-10-31 19:45 UTC, llav3ji2019 commented on css/styles.css
> +  top: 10px;
исправил

2022-10-31 21:28 UTC, llav3ji2019 commented on css/styles.css
> +  position: absolute;
исправил

2022-10-31 21:28 UTC, llav3ji2019 commented on css/styles.css
> +  height: 20px;
исправил

2022-10-31 21:29 UTC, llav3ji2019 commented on css/styles.css
> +  color: #666666;
исправил

2022-10-31 21:29 UTC, llav3ji2019 commented on css/styles.css
> +  margin-top: -99999px;
исправил

2022-10-31 21:29 UTC, llav3ji2019 commented on css/styles.css
> +.footer__item-in-footer:nth-child(3n) {
исправил

2022-11-01 08:45 UTC, fromanywhere requested changes

2022-11-01 08:45 UTC, fromanywhere commented on css/styles.css
> +  height: 100%;
Скролл сломался 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/1042969/199193824-d3b960fc-4372-4237-81f2-db104b8b401b.png">

2022-11-01 08:45 UTC, fromanywhere commented on css/styles.css
> +  display: inline-block;
Кружки чекбоксов совсем не выровнены относительно стрелки их выбора 
<img width="152" alt="image" src="https://user-images.githubusercontent.com/1042969/199194090-b69342fa-fe8a-4f3f-a298-5c8b26aa2d0e.png">

2022-11-01 08:45 UTC, fromanywhere commented on css/styles.css
> +  justify-content: center;
При узком окне левая часть приложения не доступна <img width="317" alt="image" src="https://user-images.githubusercontent.com/1042969/199194204-be9ea605-a7fa-4adc-a168-c6174a969a30.png">

2022-11-04 22:44 UTC, llav3ji2019 commented on css/styles.css
> +  position: absolute;
исправил

2022-11-04 22:45 UTC, llav3ji2019 commented on css/styles.css
> +  height: 100%;
исправил

2022-11-04 22:45 UTC, llav3ji2019 commented on css/styles.css
> +  display: inline-block;
исправил

2022-11-04 22:45 UTC, llav3ji2019 commented on css/styles.css
> +  justify-content: center;
исправил

2022-11-05 20:11 UTC, fromanywhere approved these changes
Зачтено

2022-11-05 20:11 UTC, fromanywhere commented on css/styles.css
> +.item-in-list__delete_btn:focus {
А теперь появления на ховер не хватает

2022-11-05 20:41 UTC, llav3ji2019 commented on css/styles.css
> +.item-in-list__delete_btn:focus {
когда наводимся на элемент списка, должна появляться кнопка удаления этого элемента?

2022-11-05 20:45 UTC, fromanywhere commented on css/styles.css
> +.item-in-list__delete_btn:focus {
да

2022-11-05 21:03 UTC, llav3ji2019 commented on css/styles.css
> +.item-in-list__delete_btn:focus {
если предыдущий тезис верен, то исправил

2022-11-05 21:17 UTC, fromanywhere commented on css/styles.css
> +.item-in-list__delete_btn:focus {
👍

2022-11-05 22:57 UTC, merged