Hw4 Emelyanov Pavel
ok-technopolis-autumn-2022/Emelyanov_Pavel pull request #4
Opened 2022-11-21 00:14 UTC by llav3ji2019

2022-11-21 09:48 UTC, fromanywhere requested changes
Я очень рекомендую _после_ исправления комментариев сделать перерыв, затем посмотреть на код свежим взглядом, или вообще просто попробовать написать его заново. Через несколько итераций повторяющиеся части кода уйдут (перепечатывать будет ленивее), и код станет почище

2022-11-21 09:48 UTC, fromanywhere commented on js/module/displayFunctions.js
> +export function hide(element) {
для этого придумали classList.toggle / contains

2022-11-21 09:48 UTC, fromanywhere commented on js/module/generateLi.js
> +    let deleteImage  = document.createElement('img');
а вот потому что нужно это css-ом делать, и тогда не придется в шаблонах поддерживать пути

2022-11-21 09:48 UTC, fromanywhere commented on js/module/generateLi.js
> +    let deleteBtn  = document.createElement('button');
А почему let? То, что там в поля потом дописывается, для const тоже будет работать — объект, ссылка сохранится

2022-11-21 09:48 UTC, fromanywhere commented on js/module/task.js
> +const MAX_ID_VALUE = 1000000000000;
Number.MAX_SAFE_INTEGER

2022-11-21 09:48 UTC, fromanywhere commented on js/module/task.js
> +    return Math.floor(Math.random() * max);
Совершенно ненадежно. Такое запросто может создать два одинаковых id, даже подряд. Лучше инкремент

2022-11-21 09:48 UTC, fromanywhere commented on js/index.js
> +allCheckboxes.forEach((checkbox) => {
А вот если бы было делегирование событий, то и вешать прищлось бы только один раз, и удалять потом не пришлось

2022-11-21 09:48 UTC, fromanywhere commented on js/index.js
> +    if (filterButton.value === "Completed") {
может switch?

2022-11-21 09:48 UTC, fromanywhere commented on js/index.js
> +    if ((this.checked && currentFilterValue === "Active") || (!this.checked && currentFilterValue === "Completed")) {
Во эти константы Вы потом устанете искать по всему проекту, потому что они никакой семантикой не обладают, и IDE никак не поможет (только полнотекстовым поиском). Чтобы такого не было, делают const STATE = { ACTIVE: 'Active', COMPLETED: 'completed' }, и тогда по месту использования currentFilterValue === STATE.ACTIVE

2022-11-27 03:21 UTC, llav3ji2019 commented on js/module/displayFunctions.js
> +export function hide(element) {
исправил

2022-11-27 03:21 UTC, llav3ji2019 commented on js/module/generateLi.js
> +    let deleteImage  = document.createElement('img');
обалденная мысль, которой воспользовался

2022-11-27 03:22 UTC, llav3ji2019 commented on js/module/generateLi.js
> +    let deleteBtn  = document.createElement('button');
исправил

2022-11-27 03:23 UTC, llav3ji2019 commented on js/module/task.js
> +const MAX_ID_VALUE = 1000000000000;
исправил

2022-11-27 03:23 UTC, llav3ji2019 commented on js/module/task.js
> +    return Math.floor(Math.random() * max);
understandable

2022-11-27 03:24 UTC, llav3ji2019 commented on js/index.js
> +allCheckboxes.forEach((checkbox) => {
А вот я сделал делегирование и реально стало легче. И не только тут

2022-11-27 03:24 UTC, llav3ji2019 commented on js/index.js
> +    if (filterButton.value === "Completed") {
в итоге объединил условия

2022-11-27 03:26 UTC, llav3ji2019 commented on js/index.js
> +    if ((this.checked && currentFilterValue === "Active") || (!this.checked && currentFilterValue === "Completed")) {
исправил

2022-11-27 03:29 UTC, llav3ji2019 commented
> Я очень рекомендую _после_ исправления комментариев сделать перерыв, затем посмотреть на код свежим взглядом, или вообще просто попробовать написать его заново. Через несколько итераций повторяющиеся части кода уйдут (перепечатывать будет ленивее), и код станет почище

Я сделала перерыв с js, посмотрел код на свежий взгляд, всплакнул, но заново не писал(изменял то, что есть). Несколько итераций не понадобилось, но вроде код стал почище.

2022-11-28 09:25 UTC, fromanywhere approved these changes
Зачтено

2022-11-28 09:25 UTC, fromanywhere commented on js/index.js
> +    getCheckedFilter().click();
Бросание события вот таким образом — это почти всегда заявка на переусложненное решение. Вот наверняка же можно вызвать логику обработки фильтра напрямую

2022-11-28 09:25 UTC, fromanywhere commented on js/index.js
> +    if (radioButton.className !== 'footer__radio-button') {
лучше classList.contains

2022-11-29 06:17 UTC, llav3ji2019 commented on js/index.js
> +    if (radioButton.className !== 'footer__radio-button') {
исправил

2022-11-29 06:17 UTC, llav3ji2019 commented on js/index.js
> +    getCheckedFilter().click();
исправил

2022-12-04 14:21 UTC, merged